### ISSUE TITLE
createRefresh import issue

### ISSUE THREAD

**Issue by zarnocha** [react-auth-kit/react-auth-kit#1539]
Hello. 
I think there's a bug with `createRefresh` export.
No matter how much I'm trying to import it, it stil gives me that error message: `[plugin:vite:import-analysis] Missing "./createRefresh" specifier in "react-auth-kit" package`.
I'm importing it like so: `import createRefresh from "react-auth-kit/createRefresh";`

**Comment by batuhannozkann** [comment]
did you solve it ? ı have got same error

**Comment by MohanCoderIn** [comment]
yes same error for me

**Comment by darkmatter18** [comment]
After V3, we implemented tree-shaking, so using 

```js
import createRefresh from "react-auth-kit/createRefresh";
```

It'll lower the build size.

**Comment by zarnocha** [comment]
I reinstalled it to `3.0.2-alpha.16` but there's still an error occuring: `[plugin:vite:import-analysis] Missing "./createRefresh" specifier in "react-auth-kit" package`.
I'm literally importing it like you said so:
`import createRefresh from "react-auth-kit/createRefresh";`.

Error from terminal:
```
Missing "./createRefresh" specifier in "react-auth-kit" package
01:50:00 [vite] Internal server error: Missing "./createRefresh" specifier in "react-auth-kit" package
  Plugin: vite:import-analysis
```

**Comment by imantalebizdeh** [comment]
### same error for me!
I installed the latest version: `3.0.2-alpha.16` but I still have the same error

**Comment by zarnocha** [comment]
Yes, it does work now as wanted. Thank you!

**Comment by zarnocha** [comment]
Yes, it does work now as wanted. Thank you!
